application:
  port: 8000
  host: 0.0.0.0
  secret: "a-very-long-secret"
database:
  host: "127.0.0.1"
  port: 5432
  username: "reallystick"
  password: "password"
  database_name: "reallystick"
  require_ssl: false
